### ISSUE TITLE
findAllByValue TypeError

### ISSUE THREAD

**Issue by julio8a** [jacobtyq/export-figma-svg#101]
Hello, 

Everything was working fine, but now I get this error, any idea how I can fix? or what is going on

```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at findAllByValue (/export-figma-svg/src/util/utils.js:25:17)
    at /export-figma-svg/src/util/utils.js:33:22
    at Array.reduce (<anonymous>)
    at findAllByValue (/export-figma-svg/src/util/utils.js:25:30)
    at /export-figma-svg/src/util/utils.js:33:22
    at Array.reduce (<anonymous>)
    at findAllByValue (/export-figma-svg/src/util/utils.js:25:30)
    at /export-figma-svg/src/util/utils.js:33:22
    at Array.reduce (<anonymous>)
```

**Comment by julio8a** [comment]
Figured out the problem. It was an issue in the Figma structure of the component/naming/layers!

**Comment by jacobtyq** [comment]
Hey @julio8a , could you share how you resolved this issue?

**Comment by julio8a** [comment]
@jacobtyq, there were two SVG paths that were being (grouped) subtracted in Figma. This API doesn't like it when other than SVG path data layers are inside the component. So just have SVG path layers inside the component. 

So this didn't work and was giving me the error:
![image](https://user-images.githubusercontent.com/6144462/188230315-e53ef74a-b232-4fdb-b4ae-ab2b158badb5.png)


Removing the subtract parent layer and just the two paths worked. 
![image](https://user-images.githubusercontent.com/6144462/188230416-5fd31afe-4b37-454e-a80a-a5f12452b3e7.png)


However, now I have two filled paths on top of each other and the inside of the cloud is not transparent. 


to solve this, it's best to ensure the icon is all one path when created or imported from illustrator as one path. Added this info to the icon creation process, so that we build them appropriately to avoid failed action runs. 

Hope this helps.
